name: builds

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

jobs:
  linux-build:
    name: Linux/Ubuntu build
    runs-on: ubuntu-latest
    env:
      VERSION: v1
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Update minor version
        id: tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - name: Build godot-jack (Debug)
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/nonameentername/godot-jack-ubuntu:${{ env.VERSION }}
          options: -v ${{ github.workspace }}:${{ github.workspace }} --workdir ${{ github.workspace }} -e BUILD_SHA -e TAG_VERSION
          run: |
            ./platform/ubuntu/build_debug.sh
        env:
          BUILD_SHA: ${{ steps.short-sha.outputs.sha }}
          TAG_VERSION: ${{ steps.tag.outputs.new_tag }}

      - name: Build godot-jack (Release)
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/nonameentername/godot-jack-ubuntu:${{ env.VERSION }}
          options: -v ${{ github.workspace }}:${{ github.workspace }} --workdir ${{ github.workspace }} -e BUILD_SHA -e TAG_VERSION
          run: |
            ./platform/ubuntu/build_release.sh
        env:
          BUILD_SHA: ${{ steps.short-sha.outputs.sha }}
          TAG_VERSION: ${{ steps.tag.outputs.new_tag }}

      - name: Create cache for build
        uses: actions/cache@v4
        with:
          path: addons/jack/bin
          key: linux-jack-artifacts-${{github.run_id}}

  verify-linux-build:
    name: Verify Linux/Ubuntu build
    runs-on: ubuntu-latest
    needs: linux-build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Restore cached Linux artifacts
        uses: actions/cache/restore@v4
        with:
          path: addons/jack/bin
          key: linux-jack-artifacts-${{github.run_id}}

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.3.0
          use-dotnet: false
          include-templates: false

      - name: Verify godot-jack
        run: |
          godot --headless --import || true
          godot --headless -s jack_run_scene.gd | grep godot-jack

  publish_artifacts:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Publish Artifacts
    runs-on: ubuntu-latest
    needs: [verify-linux-build]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Restore cached Linux artifacts
        uses: actions/cache/restore@v4
        with:
          path: addons/jack/bin
          key: linux-jack-artifacts-${{github.run_id}}

      - name: Update minor version
        id: tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true

      - name: Zip godot-jack artifact
        run: zip -r godot-jack${{ env.TAG_VERSION }}.zip ./addons/jack
        env:
          TAG_VERSION: ${{ steps.tag.outputs.new_tag }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
          tag_name: ${{ env.TAG_VERSION }}
          generate_release_notes: true
          make_latest: true
          files:
            godot-jack_${{ env.TAG_VERSION }}.zip
        env:
          TAG_VERSION: ${{ steps.tag.outputs.new_tag }}
